// lib/widgets/resume_preview.dart
import 'package:flutter/material.dart';
import '../models/resume_model.dart';

/// Renders the final resume using real user data in the chosen template
/// and accent color. Every template stays single-column — color is only
/// applied to headers, section titles, and skill tags, so the PDF/DOCX
/// generated by the backend stays 100% ATS-parseable.
class ResumePreview extends StatelessWidget {
  final ResumeData data;
  final String templateId;
  final String templateColor;
  const ResumePreview({super.key, required this.data, this.templateId = 'classic', this.templateColor = '#1a1a2e'});

  Color get _accent {
    final h = templateColor.replaceAll('#', '');
    try {
      return Color(int.parse('FF$h', radix: 16));
    } catch (_) {
      return const Color(0xFF1a1a2e);
    }
  }

  @override
  Widget build(BuildContext context) {
    final p = data.personal;
    final contacts = [p['phone'], p['email'], p['city']].where((v) => v != null && v.toString().isNotEmpty).map((v) => v.toString()).toList();
    if ((p['linkedin'] ?? '').isNotEmpty) contacts.add(p['linkedin']!);
    if ((p['github'] ?? '').isNotEmpty) contacts.add(p['github']!);

    final sk = data.skills;
    final tech = ((sk['technical'] as List?) ?? []).map((e) => e.toString()).where((e) => e.isNotEmpty).toList();
    final soft = ((sk['soft'] as List?) ?? []).map((e) => e.toString()).where((e) => e.isNotEmpty).toList();
    final langs = ((sk['languages'] as List?) ?? []).map((e) => e.toString()).where((e) => e.isNotEmpty).toList();
    final certs = ((sk['certifications'] as List?) ?? []).map((e) => e.toString()).where((e) => e.isNotEmpty).toList();
    final projs = data.projects.where((pr) => (pr['name'] ?? '').isNotEmpty).toList();
    final extra = data.extra.map((x) => x.toString()).where((x) => x.isNotEmpty).toList();
    final exp = data.experience.where((w) => (w['co'] ?? '').isNotEmpty).toList();
    final edus = data.education.where((e) => (e['deg'] ?? '').isNotEmpty || (e['col'] ?? '').isNotEmpty).toList();

    final ctx = _ResumeContext(
      name: p['name'] ?? '', role: p['role'] ?? '', contacts: contacts,
      summary: data.summary, exp: exp, edus: edus,
      tech: tech, soft: soft, langs: langs, certs: certs,
      projs: projs, extra: extra, accent: _accent,
    );

    switch (templateId) {
      case 'modern':
      case 'colorheader':
        return _HeaderBandLayout(ctx: ctx);
      case 'executive':
        return _ExecutiveLayout(ctx: ctx);
      case 'minimal':
        return _MinimalLayout(ctx: ctx);
      case 'bold':
        return _BoldLayout(ctx: ctx);
      case 'timeline':
        return _TimelineLayout(ctx: ctx);
      case 'compact':
        return _CompactLayout(ctx: ctx);
      case 'classic':
      default:
        return _ClassicLayout(ctx: ctx);
    }
  }
}

/// Shared data bundle passed to every layout so each one only handles presentation.
class _ResumeContext {
  final String name, role, summary;
  final List<String> contacts, tech, soft, langs, certs, extra;
  final List<dynamic> exp, edus, projs;
  final Color accent;
  _ResumeContext({
    required this.name, required this.role, required this.contacts, required this.summary,
    required this.exp, required this.edus, required this.tech, required this.soft,
    required this.langs, required this.certs, required this.projs, required this.extra,
    required this.accent,
  });
}

// ── Shared building blocks ─────────────────────────────────
Widget _heading(String text, Color accent, {bool underline = true, double size = 11}) => Padding(
  padding: const EdgeInsets.only(top: 10, bottom: 3),
  child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [
    Text(text.toUpperCase(), style: TextStyle(fontSize: size, fontWeight: FontWeight.w700, letterSpacing: 1.5, color: accent)),
    if (underline) Container(margin: const EdgeInsets.only(top: 3), height: 0.6, color: const Color(0xFFCCCCCC)),
  ]),
);

Widget _bulletList(List<dynamic> bullets) => Column(
  crossAxisAlignment: CrossAxisAlignment.start,
  children: bullets.where((b) => b.toString().isNotEmpty).map((b) => Padding(
    padding: const EdgeInsets.only(left: 12, bottom: 2),
    child: Text('• ${b.toString()}', style: const TextStyle(fontSize: 10.5, color: Color(0xFF222222), height: 1.45)),
  )).toList(),
);

Widget _skillChips(List<String> skills, Color accent, {bool solid = false}) => Wrap(
  spacing: 5, runSpacing: 5,
  children: skills.map((s) => Container(
    padding: const EdgeInsets.symmetric(horizontal: 8, vertical: 3),
    decoration: BoxDecoration(
      color: solid ? accent.withOpacity(0.9) : accent.withOpacity(0.1),
      borderRadius: BorderRadius.circular(3),
    ),
    child: Text(s, style: TextStyle(fontSize: 10, color: solid ? Colors.white : accent)),
  )).toList(),
);

Widget _jobBlock(dynamic w, Color accent) {
  final bullets = ((w['bullets'] as List?) ?? []);
  return Padding(
    padding: const EdgeInsets.only(bottom: 8),
    child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [
      Row(children: [
        Expanded(child: Text(w['des'] ?? '', style: const TextStyle(fontSize: 12, fontWeight: FontWeight.w700, color: Color(0xFF0A0A0A)))),
        Text('${w['start'] ?? ''} – ${w['end'] ?? 'Present'}', style: const TextStyle(fontSize: 10, color: Color(0xFF666666))),
      ]),
      Text('${w['co'] ?? ''}${(w['loc'] ?? '').isNotEmpty ? ' | ${w['loc']}' : ''}', style: const TextStyle(fontSize: 11, color: Color(0xFF444444), fontStyle: FontStyle.italic)),
      _bulletList(bullets),
    ]),
  );
}

Widget _eduBlock(dynamic e) {
  final colParts = [e['col'], e['grade'], e['honors']].where((v) => (v ?? '').isNotEmpty).join(' | ');
  return Padding(
    padding: const EdgeInsets.only(bottom: 6),
    child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [
      Row(children: [
        Expanded(child: Text(e['deg'] ?? '', style: const TextStyle(fontSize: 12, fontWeight: FontWeight.w600, color: Color(0xFF0A0A0A)))),
        Text(e['yr'] ?? '', style: const TextStyle(fontSize: 10, color: Color(0xFF666666))),
      ]),
      Text(colParts, style: const TextStyle(fontSize: 11, color: Color(0xFF444444), fontStyle: FontStyle.italic)),
    ]),
  );
}

Widget _projBlock(dynamic pr) => Padding(
  padding: const EdgeInsets.only(bottom: 6),
  child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [
    RichText(text: TextSpan(
      text: pr['name'] ?? '',
      style: const TextStyle(fontSize: 12, fontWeight: FontWeight.w700, color: Color(0xFF0A0A0A)),
      children: (pr['tech'] ?? '').isNotEmpty ? [TextSpan(text: ' | ${pr['tech']}', style: const TextStyle(fontWeight: FontWeight.normal, color: Color(0xFF555555), fontStyle: FontStyle.italic, fontSize: 10))] : [],
    )),
    if ((pr['desc'] ?? '').isNotEmpty) Text(pr['desc'], style: const TextStyle(fontSize: 10.5, color: Color(0xFF333333), height: 1.4)),
  ]),
);

Widget _sectionsBody(_ResumeContext ctx, {bool skillsSolid = false}) {
  final c = ctx.accent;
  return Column(crossAxisAlignment: CrossAxisAlignment.start, children: [
    if (ctx.summary.isNotEmpty) ...[
      _heading('Professional Summary', c),
      Text(ctx.summary, style: const TextStyle(fontSize: 11, color: Color(0xFF333333), height: 1.6)),
    ],
    if (ctx.exp.isNotEmpty) ...[
      _heading('Work Experience', c),
      ...ctx.exp.map((w) => _jobBlock(w, c)),
    ],
    if (ctx.edus.isNotEmpty) ...[
      _heading('Education', c),
      ...ctx.edus.map((e) => _eduBlock(e)),
    ],
    if (ctx.tech.isNotEmpty) ...[
      _heading('Technical Skills', c),
      _skillChips(ctx.tech, c, solid: skillsSolid),
    ],
    if (ctx.soft.isNotEmpty) ...[
      _heading('Core Competencies', c),
      _skillChips(ctx.soft, c, solid: skillsSolid),
    ],
    if (ctx.projs.isNotEmpty) ...[
      _heading('Key Projects', c),
      ...ctx.projs.map((pr) => _projBlock(pr)),
    ],
    if (ctx.certs.isNotEmpty) ...[
      _heading('Certifications', c),
      ...ctx.certs.map((x) => Padding(padding: const EdgeInsets.only(bottom: 2), child: Text('• $x', style: const TextStyle(fontSize: 10.5, color: Color(0xFF333333))))),
    ],
    if (ctx.langs.isNotEmpty) ...[
      _heading('Languages', c),
      _skillChips(ctx.langs, c, solid: skillsSolid),
    ],
    if (ctx.extra.isNotEmpty) ...[
      _heading('Achievements & Activities', c),
      ...ctx.extra.map((x) => Padding(padding: const EdgeInsets.only(bottom: 2), child: Text('• $x', style: const TextStyle(fontSize: 10.5, color: Color(0xFF333333))))),
    ],
    const SizedBox(height: 16),
    Center(child: Text('Generated by ResumeAI Pro • ATS Optimized', style: TextStyle(fontSize: 9, color: Colors.grey[400]))),
  ]);
}

// ── 1. Classic ──────────────────────────────────────────────
class _ClassicLayout extends StatelessWidget {
  final _ResumeContext ctx;
  const _ClassicLayout({required this.ctx});
  @override
  Widget build(BuildContext context) {
    return Container(color: Colors.white, padding: const EdgeInsets.all(20), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [
      Center(child: Text(ctx.name, style: TextStyle(fontSize: 20, fontWeight: FontWeight.w700, color: ctx.accent, fontFamily: 'Georgia', letterSpacing: 0.5))),
      if (ctx.role.isNotEmpty) Center(child: Text(ctx.role, style: TextStyle(fontSize: 12, color: ctx.accent, fontFamily: 'Georgia'))),
      const SizedBox(height: 4),
      Center(child: Text(ctx.contacts.join(' | '), style: const TextStyle(fontSize: 10, color: Color(0xFF555555)), textAlign: TextAlign.center)),
      const SizedBox(height: 8),
      Container(height: 1.5, color: ctx.accent),
      _sectionsBody(ctx),
    ]));
  }
}

// ── 2. Header Band (Modern / Colorheader) ──────────────────
class _HeaderBandLayout extends StatelessWidget {
  final _ResumeContext ctx;
  const _HeaderBandLayout({required this.ctx});
  @override
  Widget build(BuildContext context) {
    return Container(color: Colors.white, child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [
      Container(
        width: double.infinity, color: ctx.accent, padding: const EdgeInsets.all(18),
        child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [
          Text(ctx.name, style: const TextStyle(fontSize: 20, fontWeight: FontWeight.w700, color: Colors.white)),
          if (ctx.role.isNotEmpty) Text(ctx.role, style: TextStyle(fontSize: 12, color: Colors.white.withOpacity(0.9))),
          const SizedBox(height: 4),
          Text(ctx.contacts.join('  •  '), style: TextStyle(fontSize: 10, color: Colors.white.withOpacity(0.75))),
        ]),
      ),
      Padding(padding: const EdgeInsets.all(18), child: _sectionsBody(ctx, skillsSolid: true)),
    ]));
  }
}

// ── 3. Executive ─────────────────────────────────────────────
class _ExecutiveLayout extends StatelessWidget {
  final _ResumeContext ctx;
  const _ExecutiveLayout({required this.ctx});
  @override
  Widget build(BuildContext context) {
    return Container(color: Colors.white, padding: const EdgeInsets.all(20), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [
      Center(child: Text(ctx.name.toUpperCase(), style: const TextStyle(fontSize: 19, fontWeight: FontWeight.w700, letterSpacing: 2, fontFamily: 'Times New Roman'))),
      Center(child: Container(margin: const EdgeInsets.symmetric(vertical: 4), height: 1.5, width: 120, color: ctx.accent)),
      if (ctx.role.isNotEmpty) Center(child: Text(ctx.role, style: TextStyle(fontSize: 12, color: ctx.accent, fontStyle: FontStyle.italic, letterSpacing: 1))),
      const SizedBox(height: 4),
      Center(child: Text(ctx.contacts.join('  |  '), style: const TextStyle(fontSize: 10, color: Color(0xFF555555)))),
      _sectionsBody(ctx),
    ]));
  }
}

// ── 4. Minimalist ───────────────────────────────────────────
class _MinimalLayout extends StatelessWidget {
  final _ResumeContext ctx;
  const _MinimalLayout({required this.ctx});
  @override
  Widget build(BuildContext context) {
    return Container(color: Colors.white, padding: const EdgeInsets.all(24), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [
      Text(ctx.name, style: TextStyle(fontSize: 21, fontWeight: FontWeight.w300, letterSpacing: 4, color: ctx.accent)),
      if (ctx.role.isNotEmpty) Text(ctx.role.toUpperCase(), style: TextStyle(fontSize: 10, color: ctx.accent.withOpacity(0.7), letterSpacing: 2)),
      const SizedBox(height: 6),
      Text(ctx.contacts.join('   '), style: const TextStyle(fontSize: 10, color: Color(0xFFAAAAAA))),
      _sectionsBody(ctx),
    ]));
  }
}

// ── 5. Bold Accent Lines ───────────────────────────────────
class _BoldLayout extends StatelessWidget {
  final _ResumeContext ctx;
  const _BoldLayout({required this.ctx});
  @override
  Widget build(BuildContext context) {
    return Container(color: Colors.white, padding: const EdgeInsets.all(20), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [
      Text(ctx.name, style: TextStyle(fontSize: 22, fontWeight: FontWeight.w700, color: ctx.accent)),
      if (ctx.role.isNotEmpty) Text(ctx.role, style: const TextStyle(fontSize: 12, color: Color(0xFF555555))),
      Text(ctx.contacts.join('  •  '), style: const TextStyle(fontSize: 10, color: Color(0xFF888888))),
      Container(margin: const EdgeInsets.symmetric(vertical: 8), height: 3, color: ctx.accent),
      Container(
        padding: const EdgeInsets.only(left: 10),
        decoration: BoxDecoration(border: Border(left: BorderSide(color: ctx.accent, width: 3))),
        child: _sectionsBody(ctx),
      ),
    ]));
  }
}

// ── 6. Timeline with Dots ──────────────────────────────────
class _TimelineLayout extends StatelessWidget {
  final _ResumeContext ctx;
  const _TimelineLayout({required this.ctx});
  @override
  Widget build(BuildContext context) {
    return Container(color: Colors.white, padding: const EdgeInsets.all(20), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [
      Text(ctx.name, style: TextStyle(fontSize: 20, fontWeight: FontWeight.w700, color: ctx.accent)),
      if (ctx.role.isNotEmpty) Text(ctx.role, style: const TextStyle(fontSize: 12, color: Color(0xFF666666))),
      Text(ctx.contacts.join('  •  '), style: const TextStyle(fontSize: 10, color: Color(0xFF888888))),
      Container(margin: const EdgeInsets.symmetric(vertical: 8), height: 2, color: ctx.accent),
      if (ctx.summary.isNotEmpty) ...[
        _heading('Professional Summary', ctx.accent),
        Text(ctx.summary, style: const TextStyle(fontSize: 11, color: Color(0xFF333333), height: 1.6)),
      ],
      if (ctx.exp.isNotEmpty) ...[
        _heading('Work Experience', ctx.accent, underline: false),
        ...ctx.exp.asMap().entries.map((entry) {
          final i = entry.key; final w = entry.value;
          final bullets = ((w['bullets'] as List?) ?? []);
          return Padding(
            padding: const EdgeInsets.only(bottom: 10),
            child: Row(crossAxisAlignment: CrossAxisAlignment.start, children: [
              Container(width: 9, height: 9, margin: const EdgeInsets.only(top: 4, right: 10),
                decoration: BoxDecoration(color: i == 0 ? ctx.accent : ctx.accent.withOpacity(0.4), shape: BoxShape.circle)),
              Expanded(child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [
                Row(children: [
                  Expanded(child: Text(w['des'] ?? '', style: const TextStyle(fontSize: 12, fontWeight: FontWeight.w700))),
                  Text('${w['start'] ?? ''} – ${w['end'] ?? 'Present'}', style: const TextStyle(fontSize: 10, color: Color(0xFF666666))),
                ]),
                Text('${w['co'] ?? ''}${(w['loc'] ?? '').isNotEmpty ? ' | ${w['loc']}' : ''}', style: const TextStyle(fontSize: 11, color: Color(0xFF444444), fontStyle: FontStyle.italic)),
                _bulletList(bullets),
              ])),
            ]),
          );
        }),
      ],
      if (ctx.edus.isNotEmpty) ...[_heading('Education', ctx.accent), ...ctx.edus.map((e) => _eduBlock(e))],
      if (ctx.tech.isNotEmpty) ...[_heading('Technical Skills', ctx.accent), _skillChips(ctx.tech, ctx.accent)],
      if (ctx.soft.isNotEmpty) ...[_heading('Core Competencies', ctx.accent), _skillChips(ctx.soft, ctx.accent)],
      if (ctx.projs.isNotEmpty) ...[_heading('Key Projects', ctx.accent), ...ctx.projs.map((pr) => _projBlock(pr))],
      if (ctx.certs.isNotEmpty) ...[_heading('Certifications', ctx.accent), ...ctx.certs.map((x) => Padding(padding: const EdgeInsets.only(bottom: 2), child: Text('• $x', style: const TextStyle(fontSize: 10.5, color: Color(0xFF333333)))))],
      if (ctx.langs.isNotEmpty) ...[_heading('Languages', ctx.accent), _skillChips(ctx.langs, ctx.accent)],
      if (ctx.extra.isNotEmpty) ...[_heading('Achievements & Activities', ctx.accent), ...ctx.extra.map((x) => Padding(padding: const EdgeInsets.only(bottom: 2), child: Text('• $x', style: const TextStyle(fontSize: 10.5, color: Color(0xFF333333)))))],
      const SizedBox(height: 16),
      Center(child: Text('Generated by ResumeAI Pro • ATS Optimized', style: TextStyle(fontSize: 9, color: Colors.grey[400]))),
    ]));
  }
}

// ── 7. Compact & Dense ─────────────────────────────────────
class _CompactLayout extends StatelessWidget {
  final _ResumeContext ctx;
  const _CompactLayout({required this.ctx});
  @override
  Widget build(BuildContext context) {
    return Container(color: Colors.white, padding: const EdgeInsets.all(16), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [
      Text(ctx.name, style: TextStyle(fontSize: 17, fontWeight: FontWeight.w700, color: ctx.accent)),
      if (ctx.role.isNotEmpty) Text(ctx.role, style: TextStyle(fontSize: 11, fontWeight: FontWeight.w500, color: ctx.accent)),
      Container(
        margin: const EdgeInsets.symmetric(vertical: 4),
        padding: const EdgeInsets.only(bottom: 4),
        decoration: BoxDecoration(border: Border(bottom: BorderSide(color: ctx.accent, width: 1))),
        child: Text(ctx.contacts.join('  •  '), style: const TextStyle(fontSize: 10, color: Color(0xFF666666))),
      ),
      _sectionsBody(ctx),
    ]));
  }
}
